### ISSUE TITLE
Create map compoinent design document

### ISSUE THREAD

**Issue by brylie** [GeoLibre/libre-gke#1]
The map is central to this application. It needs to be described in simple terms with diagrams.
## Task
- [x] Create [map design document](https://github.com/GeoLibre/libre-gke/blob/master/docs/map.md)
- [ ] Describe key features of map
- [ ] Create basic diagram of map

**Comment by brylie** [comment]
@GeoLibre/design please review the [map design document](https://github.com/GeoLibre/libre-gke/blob/master/docs/map.md). Add any thoughts, questions, or ideas as needed.
